AWSTemplateFormatVersion: 2010-09-09
Description: >-
  todo-list-serverless

Transform:
- AWS::Serverless-2016-10-31

Globals:
    Function:
        Environment:
          Variables:
            TABLE_NAME: !Ref Task
            ENDPOINT_OVERRIDE: ""

Resources:
  getAllTasks:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-all-tasks.getAllTasksHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 15
      Description: Get all tasks from the DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Task
      Events:
        Api:
          Type: Api
          Properties:
            Path: /tasks
            Method: GET

  getTaskById:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-task-by-id.getTaskByIdHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Description: Get one task by id from the DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Task
      Events:
        Api:
          Type: Api
          Properties:
            Path: /tasks/{id}
            Method: GET

  createTask:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/create-task.createTaskHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Description: Create a new task in the DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Task
      Events:
        Api:
          Type: Api
          Properties:
            Path: /tasks
            Method: POST

  updateTask:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/update-task.updateTaskHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Description: Update a task in the DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Task
      Events:
        Api:
          Type: Api
          Properties:
            Path: /tasks/{id}
            Method: PUT

  deleteTask:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/delete-task.deleteTaskHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Description: Delete a task from the DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Task
      Events:
        Api:
          Type: Api
          Properties:
            Path: /tasks/{id}
            Method: DELETE


  Task:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
